### ISSUE TITLE
Incorrect error melding als je niet goed aanmeld.

### ISSUE THREAD

**Issue by Yornik** [CyberRegister/CyberRegister#29]
Krijg de error code

> Deze combinatie van e-mailadres en wachtwoord is niet geldig.

Terwijl ik inlog met met mijn cyber code, en niet met mijn e-mailadres.

**Comment by annejan** [comment]
Ik zal de (default) melding verbeteren want inderdaad we loggen niet in met email.

Thanks voor deze cybermelding en fix!
